### ISSUE TITLE
[Bug] Playnite crash while using drag & drop

### ISSUE THREAD

**Issue by SparrowBrain** [dragonmc77/Listicles#8]
![image](https://github.com/dragonmc77/Listicles/assets/17652035/a4adcd4f-89f6-483d-a50e-899b98e81d4c)
Listicles crashed Playnite while using drag & drop and otherwise re-arranging a listicle. Listicle contains games and stubs.

```
02-06 10:11:19.798|ERROR|PlayniteApplication:Unhandled exception occured.
System.InvalidCastException: Unable to cast object of type 'MS.Internal.NamedObject' to type 'Playnite.SDK.Models.Game'.
   at Listicles.ListiclesView.lvGames_MouseMove(Object sender, MouseEventArgs e) in C:\Users\Qwx\Documents\src\Listicles\ListiclesView.xaml.cs:line 101
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 71
02-06 10:11:19.826|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: c58859e2-9b2e-4237-be57-8fbbd4041fda
```

**Comment by SparrowBrain** [comment]
Additionally drag&drop sometimes moves the wrong item. I click on one item, drop it, and a different item is actually moved.

**Comment by Whitechapel-1888** [comment]
I am not 100% sure, but it seems drag & drop bugs out the extension in general. While it doesn't crash for me (unless I drag & drop too often), some functionality like adding a new listicle becomes unstable (it overwrites existing ones or does nothing).

Maybe there's an issue with the extension updating the index value inside of the listicles.xml?

**Comment by dragonmc77** [comment]
Looking into this. The drag & drop code was community submitted and there seems to be some problem with it. I am reviewing it and may need to remove it temporarily until I can troubleshoot it properly.
